### PR TITLE
Feat/motives

### PR DESCRIPTION
**Pull request by karstenlenz**
Please review my implementation of the second user story:
https://github.com/karstenlenz/capstone-project/issues/4

You can now choose your most important needs in step 1 to be assigned the best-matching personality type. In step 2 you will get one out of nine questionnaires to answer.

### CODE REVIEW

**Review by marwinburesch — APPROVED** [review]
Good work! I like that you made snapshot test etc. and the project seems to run at a good pace.
There are some unexpected commits in here, which results in a lot of changes. I had to force myself a little to look through the PR :D 
Be careful with the size of your components (code wise), some of them are getting quite big already

Cheers, 🐜

**Comment by karstenlenz** [comment]
> Good work! I like that you made snapshot test etc. and the project seems to run at a good pace.
> There are some unexpected commits in here, which results in a lot of changes. I had to force myself a little to look through the PR :D
> Be careful with the size of your components (code wise), some of them are getting quite big already
> 
> Cheers, 🐜

Thanks you for the review! I can understand that this PR was a bit complex, sorry about that. I think it is in part because the first PR hadn't been merged, so that all the commits from PR#1 also showed up here.
I extracted the MotiveButtons into a separate componenent like you suggested. Motives.js is now much cleaner, thanks! When I start with styling I will double-check all my components and see what I need to split up.

**Review by annaleaschroeder — COMMENTED** [review]
Great implementation, Karsten! 
I clicked through various combinations and found no mistakes.
I noticed a few little things from the user's perspective: 
- Should the user be able to return to the original screen (selection by importance) after starting a questionnaire?  At the moment this function is disabled. 
- In the mobile view the font size for the questions seems a bit oversized, or questions and answers do not necessarily fit on a screen without scrolling.

**Comment by karstenlenz** [comment]
Thank you for testing, @annaleaschroeder !

>     * Should the user be able to return to the original screen (selection by importance) after starting a questionnaire?  At the moment this function is disabled.
Currently this is not possible because we don't want the user to cherry-pick the questionnaire. I will discuss this with my psychology partner to see what will be the best procedure.

>     * In the mobile view the font size for the questions seems a bit oversized, or questions and answers do not necessarily fit on a screen without scrolling.
Yes that's true! I will deal with the styles later, when I start with the design.

**Pull request merged**
