### PR TITLE
Feat/result details

### PR DESCRIPTION
**Pull request by karstenlenz**
Please review my code. 

User Story: https://github.com/karstenlenz/capstone-project/issues/10

### CODE REVIEW

**Review by ninasander — APPROVED** [review]
Nice work! Personally, I couldn't find anything that needs fixing or improvement.

**Comment by manuelpapa** [comment]
Super well done! 
maybe in the questionnaire you can think of switching the question `<h2>` to another tag, just to structure the semantic order a little better. Otherwise, the page is only made of headlines. That is no problem but if you are interested in a better google ranking, you can think of an optimization.

**Comment by mskradde** [comment]
Good Job Karsten. The code looks good to me. Maybe you could pay more attention to the git-history in future branches. In this branch is not really clear to me what belongs to the "feat/result-details" branch and what should be committed into an other branch.

**Comment by karstenlenz** [comment]
> Super well done!
> maybe in the questionnaire you can think of switching the question `<h2>` to another tag, just to structure the semantic order a little better. Otherwise, the page is only made of headlines. That is no problem but if you are interested in a better google ranking, you can think of an optimization.

Thanks for the review! I don't think the questionnaire page needs to rank on Google, but you are right, that the headline order is a bit weird. I swapped the h2 and h3 so that it makes more sense.

**Pull request merged**
